### PR TITLE
feat: allow routes without curves

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Ah, I made a mistake rebasing this, sorry. Will retry.

**Comment by michielbdejong** [comment]
Rebase fixed - @sharafian can you review the last commit of this PR?

**Comment by michielbdejong** [comment]
@emschwartz can you review https://github.com/interledgerjs/ilp-routing/pull/45/commits/df09eda59b8f98f87348e3aa4e02ee769fe34047??

**Comment by sentientwaffle** [comment]
This branch should be rebased on master. I don't think the changes in `src/lib/routing-tables.js` are needed anymore.

**Pull request merged**
